export default [
    { id: 71, name: 'Miss Janice Wolf Savings', balance: 10_000.99 },
    { id: 45, name: 'Prof. Emery Shanahan IV Checking', balance: 8501.74 },
    { id: 48, name: 'Miss Fay Champlin Savings', balance: 8501 },
    { id: 80, name: 'Dr. Lacy Schuster Checking', balance: 8000.5 },
    { id: 36, name: 'Darron McLaughlin Checking', balance: 7901 },
    { id: 25, name: 'Nyasia Grady IV Savings', balance: 7500.5 },
    { id: 34, name: 'Owen Kovacek Checking', balance: 7400.5 },
    { id: 44, name: 'Antone Gerhold Savings', balance: 7200.75 },
    { id: 87, name: 'Rosario Bogan Checking', balance: 7101.74 },
    { id: 75, name: 'Mrs. Brigitte Dooley Savings', balance: 7100.25 },
    { id: 73, name: 'Granville Nienow Savings', balance: 7001.49 },
    { id: 38, name: 'Prof. Geoffrey Reinger Checking', balance: 6700.5 },
    { id: 83, name: 'Naomi Bailey Checking', balance: 6400.99 },
    { id: 76, name: 'Prof. Keyshawn Huel Checking', balance: 6400.5 },
    { id: 72, name: 'Granville Nienow Checking', balance: 6301.24 },
    { id: 14, name: 'Charlene Bernhard V Checking', balance: 6201.74 },
    { id: 6, name: 'Dr. Sean Satterfield DVM Checking', balance: 6200.75 },
    { id: 23, name: 'Dr. Gabe Zulauf DVM Checking', balance: 6100 },
    { id: 20, name: 'Prof. Keith Schinner Checking', balance: 5900.5 },
    { id: 86, name: 'Mr. Dawson Skiles DVM Savings', balance: 5701 },
    { id: 15, name: 'Charlene Bernhard V Savings', balance: 5499.75 },
    { id: 53, name: 'Cynthia Hackett Checking', balance: 5300.5 },
    { id: 28, name: 'Margarita Langworth Checking', balance: 5099.51 },
    { id: 30, name: 'Prof. Madge Windler II Checking', balance: 5001.25 },
    { id: 90, name: 'Pauline White Checking', balance: 4800 },
    { id: 35, name: 'Owen Kovacek Savings', balance: 4700 },
    { id: 33, name: 'Raoul Leuschke Checking', balance: 4601.5 },
    { id: 92, name: 'Jedediah Marvin Checking', balance: 4300 },
    { id: 50, name: 'Jamir Nikolaus Savings', balance: 4200.99 },
    { id: 96, name: 'Barney Schaden Checking', balance: 4000.51 },
    { id: 81, name: 'Rowland Fadel Checking', balance: 4000.5 },
    { id: 65, name: 'Berniece White IV Savings', balance: 3900.25 },
    { id: 93, name: 'Gerda Koepp Checking', balance: 3501.5 },
    { id: 22, name: 'Ed Jones Checking', balance: 3499.75 },
    { id: 32, name: 'Nola Hermiston Savings', balance: 3400.99 },
    { id: 74, name: 'Mrs. Brigitte Dooley Checking', balance: 3300.75 },
    { id: 26, name: 'Jabari Wisoky Checking', balance: 3300 },
    { id: 88, name: 'Zachary Wisoky IV Checking', balance: 3300 },
    { id: 78, name: 'Prof. Braden Sauer DVM Checking', balance: 3200.75 },
    { id: 63, name: 'Quinn Mayert Checking', balance: 3100.75 },
    { id: 91, name: 'Prof. Kianna Wuckert I Checking', balance: 3100.5 },
    { id: 95, name: 'Miss Scarlett Armstrong DVM Checking', balance: 3100 },
    { id: 99, name: 'Donnie Bernier Checking', balance: 3100 },
    { id: 57, name: 'Lia Shanahan Savings', balance: 3000.75 },
    { id: 19, name: 'Neva Nolan IV Checking', balance: 2901.229_999_999_999_6 },
    { id: 37, name: 'Darron McLaughlin Savings', balance: 2900.99 },
    { id: 0, name: 'Kristina Koch MD Checking', balance: 2900.75 },
    { id: 42, name: 'Gilberto Swaniawski Savings', balance: 2900.5 },
    { id: 59, name: 'Declan Borer DVM Checking', balance: 2900 },
    { id: 7, name: 'Dr. Sean Satterfield DVM Savings', balance: 2800.5 },
    { id: 55, name: 'Brennon Rowe Savings', balance: 2800.5 },
    { id: 69, name: 'Albertha McClure Checking', balance: 2800 },
    { id: 4, name: 'Abigail Price Checking', balance: 2699.01 },
    { id: 54, name: 'Brennon Rowe Checking', balance: 2601.25 },
    { id: 18, name: 'Horacio Marvin MD Savings', balance: 2600.49 },
    { id: 13, name: 'Kelvin Volkman Savings', balance: 2600 },
    { id: 11, name: 'Vicenta Walsh Checking', balance: 2401.25 },
    { id: 27, name: 'Ada Cronin DVM Checking', balance: 2299.75 },
    { id: 41, name: 'Gilberto Swaniawski Checking', balance: 2000.989_999_999_999_8 },
    { id: 12, name: 'Kelvin Volkman Checking', balance: 2000 },
    { id: 94, name: "Deborah O'Keefe Checking", balance: 2000 },
    { id: 85, name: 'Mr. Dawson Skiles DVM Checking', balance: 1900.25 },
    { id: 21, name: 'Miss Thalia Mosciski Checking', balance: 1900 },
    { id: 31, name: 'Nola Hermiston Checking', balance: 1800.99 },
    { id: 70, name: 'Miss Janice Wolf Checking', balance: 1700 },
    { id: 49, name: 'Jamir Nikolaus Checking', balance: 1501 },
    { id: 61, name: 'Prof. Santa Turcotte Jr. Savings', balance: 1500.5 },
    { id: 68, name: 'Morgan Goodwin Checking', balance: 1500.5 },
    { id: 64, name: 'Berniece White IV Checking', balance: 1400 },
    { id: 67, name: 'Aracely Wuckert Savings', balance: 1400 },
    { id: 77, name: 'Eda Morissette Checking', balance: 1300.989_999_999_999_8 },
    { id: 66, name: 'Aracely Wuckert Checking', balance: 1300 },
    { id: 62, name: 'Lea Jacobson Checking', balance: 1200.75 },
    { id: 46, name: 'Katlyn Huels Checking', balance: 1200 },
    { id: 47, name: 'Miss Fay Champlin Checking', balance: 1200 },
    { id: 52, name: 'Marilyne Bins II Savings', balance: 1100.99 },
    { id: 8, name: 'Prof. Amely Rippin Checking', balance: 1000.99 },
    { id: 17, name: 'Horacio Marvin MD Checking', balance: 1000.5 },
    { id: 84, name: 'Naomi Bailey Savings', balance: 1000 },
    { id: 5, name: 'Alaina VonRueden Checking', balance: 900 },
    { id: 82, name: 'Rowland Fadel Savings', balance: 900 },
    { id: 97, name: 'Prof. Cecil Trantow Checking', balance: 700.25 },
    { id: 10, name: 'Maureen Simonis PhD Checking', balance: 700 },
    { id: 29, name: 'Delia Collier Checking', balance: 700 },
    { id: 9, name: 'Constance Howe Checking', balance: 600 },
    { id: 43, name: 'Antone Gerhold Checking', balance: 600 },
    { id: 58, name: 'Jamar Leffler Checking', balance: 600 },
    { id: 1, name: 'Nils Frami I Checking', balance: 0 },
    { id: 2, name: 'Ms. Kelsi Fahey Checking', balance: 0 },
    { id: 3, name: 'Ms. Kelsi Fahey Savings', balance: 0 },
    { id: 16, name: 'Nikko Bartell Checking', balance: 0 },
    { id: 24, name: 'Nyasia Grady IV Checking', balance: 0 },
    { id: 39, name: 'Prof. Geoffrey Reinger Savings', balance: 0 },
    { id: 40, name: 'Althea Thiel Checking', balance: 0 },
    { id: 51, name: 'Marilyne Bins II Checking', balance: 0 },
    { id: 56, name: 'Lia Shanahan Checking', balance: 0 },
    { id: 60, name: 'Prof. Santa Turcotte Jr. Checking', balance: 0 },
    { id: 79, name: 'Ms. Marjolaine Hamill V Checking', balance: 0 },
    { id: 89, name: 'Bonita Kirlin Checking', balance: 0 },
    { id: 98, name: 'Miss Violet Schimmel Checking', balance: 0 },
];
